on:
  push: 
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: nix-shell .github/workflows/branch/shell.nix --argstr expected "^init/.*$"
          --command branch
  check:
    needs:
      - branch
    runs-on: ubuntu-latest
    steps:
      - run: true
  test-init-main:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: "nix-shell .github/workflows/test-init-main/shell.nix --argstr token\
          \ \"${{ secrets.TOKEN }}\" --argstr sed \"/nix/store/4r46xaa0zkql7dmf8ymhhpkqs9yd39df-gnused-4.8/bin/sed\
          \ \\\n  -e \"s#on#on#\" \\\n  -e \"s###\"\
          \ \\\n  -e \"s#with#with#\" \\\n  -e \"\
          w${1}\"\n\" --command test-init-main"
name: test
