on:
  push: 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: true
  test-init-main:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: nix-shell .github/workflows/test-init-main/shell.nix --argstr token "${{
          secrets.TOKEN }}" --argstr committer-user "${COMMITTER_USER}" --argstr committer-email
          ${COMMITTER_EMAIL} --command test-init-main
name: test
