name: test
on:
  push: 
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - run: TARGET=^init/.* && [[ ${GITHUB_REF_NAME} =~ ${TARGET} ]]
  versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: if [ -f flake.lock ]; then ! cat flake.lock | jq --raw-output "$( cat
          .github/workflows/versions.txt )" --exit-status ; fi
  pre-check:
    runs-on: ubuntu-latest
    needs:
      - branch
    steps:
      - run: true
  check:
    runs-on: ubuntu-latest
    needs:
      - pre-check
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_configs: access-tokens = github.com=${{ secrets.token }}
      - run: cd .github/workflows/check && nix develop --command check ""
