jobs:
  check:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
    - run: nix-shell .github/workflows/check/shell.nix --arg test-home true --command
        check
  pre-check:
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
    - run: nix-shell .github/workflows/check/shell.nix --command check
name: test
on:
  push: 
